### ISSUE TITLE
segmentation fault on launch

### ISSUE THREAD

**Issue by emctague** [netPark/node-openalpr#24]
I've copied the example (with a different image file, of course) on Arch Linux 64-bit, node v8.3.0, and I get:

````
[1]    3626 segmentation fault (core dumped)  node index.js
````

Could this be due to a change in the newer versions of OpenALPR?

**Comment by kjlaw89** [comment]
@emctague at this point I'm no longer maintaining this project. @sneko Appears to have a newer fork going for OpenALPR 2.3 that might be worth checking out: https://github.com/Sneko/node-openalpr

**Comment by emctague** [comment]
Ah, thank you. I got it to work anwyays.
