### ISSUE TITLE
Segmentation fault (core dumped) Ubuntu 14.04 x64 node v5.0.0

### ISSUE THREAD

**Issue by rrmdn** [netPark/node-openalpr#6]
Hi,

I got this error whenever i run your example,

working
Segmentation fault (core dumped)

Is that my server's availability or something?
Thanks

**Comment by kjlaw89** [comment]
This issue should be good now. Needed the newest header files for OpenALPR 2.2. Was able to compile and test against my Linux setup.

**Comment by richiepreece** [comment]
I get a similar crash when running the demo. When I install alpr v2.2.0 I get the following error:

```
richie@IRONHIDE:/mnt/c/git/plates$ node alprtest.js
libdc1394 error: Failed to initialize libdc1394
working
working
working
working
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
queued
Segmentation fault (core dumped)
```

However on alpr v2.3.0 I get:

```
richie@IRONHIDE:/mnt/c/git/plates$ node alprtest.js
libdc1394 error: Failed to initialize libdc1394
working
working
working
Segmentation fault (core dumped)
```

Thanks for your help in advance.

**Comment by sneko** [comment]
@richiepreece 

I fixed an issue with the same error, may it could help someone : 
https://github.com/Sneko/node-openalpr

#22
